Repository Deloitte-Desafio/service-appointment, pull requests merged in 2025-06, with the labels that each got.

#39 Criação das migration com o Flyway
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__create_tables.sql
  src/main/resources/db/migration/V2__populate_tables.sql
Labels: enhancement

#44 Fix de Requests
  src/main/java/com/deloitte/service_appointment/DTOs/DisponibilidadeRequestDTO.java
  src/main/java/com/deloitte/service_appointment/DTOs/Mappers/AgendamentoMapper.java
  src/main/java/com/deloitte/service_appointment/DTOs/ServicoRequestDTO.java
  src/main/java/com/deloitte/service_appointment/Entities/Disponibilidade.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/AgendamentoServiceImpl.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/DisponibilidadeServiceImpl.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/ServicoServiceImp.java
Labels: fix

#47 Adição de documentação com Swagger
  pom.xml
  src/main/resources/application.properties
Labels: documentation, enhancement

#49 Update Específico de User (ainda sem jwt,auth)
  pom.xml
  src/main/java/com/deloitte/service_appointment/Controllers/UserController.java
  src/main/java/com/deloitte/service_appointment/DTOs/User/UserUpdateDTO.java
  src/main/java/com/deloitte/service_appointment/DTOs/UserResponseDTO.java
  src/main/java/com/deloitte/service_appointment/Repositories/UserRepository.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/UserServiceImpl.java
  src/main/java/com/deloitte/service_appointment/Services/UserService.java
  src/main/java/com/deloitte/service_appointment/config/SecurityConfig.java
Labels: enhancement

#62 Criação de consulta de agendamentos futuros
  src/main/java/com/deloitte/service_appointment/Controllers/AgendamentoController.java
  src/main/java/com/deloitte/service_appointment/DTOs/Agendamento/AgendamentoDashboardDTO.java
  src/main/java/com/deloitte/service_appointment/Repositories/AgendamentoRepository.java
  src/main/java/com/deloitte/service_appointment/Services/AgendamentoService.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/AgendamentoServiceImpl.java
Labels: enhancement

#69 EndPoint User Logado
  src/main/java/com/deloitte/service_appointment/Controllers/AuthControler.java
  src/main/java/com/deloitte/service_appointment/Repositories/UserRepository.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/AuthorizationService.java
Labels: good first issue

#72 Modificação dos usuários inseridos
  src/main/resources/db/migration/V3__more_inserts.sql
Labels: fix

#73 Todas as rotas permitidas
  src/main/java/com/deloitte/service_appointment/Controllers/AgendamentoController.java
  src/main/java/com/deloitte/service_appointment/config/SecurityConfig.java
  src/main/resources/db/migration/V3__more_inserts.sql
Labels: fix

#78 Ajuste no mapper de agendamento e controllers
  src/main/java/com/deloitte/service_appointment/DTOs/Mappers/AgendamentoMapper.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/AgendamentoServiceImpl.java
Labels: fix

#80 Criação de rota em disponibilidade
  src/main/java/com/deloitte/service_appointment/Controllers/DisponibilidadeController.java
  src/main/java/com/deloitte/service_appointment/Repositories/DisponibilidadeRepository.java
  src/main/java/com/deloitte/service_appointment/Services/DisponibilidadeService.java
  src/main/java/com/deloitte/service_appointment/Services/Impl/DisponibilidadeServiceImpl.java
  src/main/resources/db/migration/V3__more_inserts.sql
Labels: enhancement
